{% set name = "gobject-introspection" %}
{% set major = "1.58" %}
{% set patch = "2" %}
{% set version = major ~ "." ~ patch %}
{% set sha256 = "2a5e0f69459af7ca4c41b8f4e19d9c80ddf877834bb0e7fdd420e2495ae2eda8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/GNOME/sources/{{ name }}/{{ major }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - windows-python-cmd.patch
    - meson-rpaths.patch  # [linux]
    - gcc7-rpath-link.patch  # [linux]

build:
  number: 1001
  skip: true  # [py<35]

requirements:
  build:
    - {{posix}}bison
    - {{posix}}flex
    - ninja
    - {{posix}}patch
    - {{native}}pkg-config
    - {{ compiler('c') }}
  host:
    - meson
    - cairo
    - gettext  # [osx]
    - glib
    - libffi
    - python
  run:
    - glib
    - libffi
    - python

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - g-ir-scanner --help  # [not win]
    - g-ir-compiler --help  # [not win]

about:
  home: https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
  license: LGPLv2+
  license_family: LGPL
  license_file: COPYING
  summary: 'Middleware for binding GObject-based code to other languages.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
