appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZkC0NE2nMEBiOBJBRiVeQLiagQnZPpn/pJp3hWVamVaBtnBBW5aj8SJ6B9TI4R85Ue3GMfjq4iDFB6JFFC6HB3xtUJy6D1PtTDJvgQZuhX8mEIVw7Tz6ZlkD0T09Am9lCO7/drhrw8qcBr4Ys1M+xL9gazdK5/1ZdHX8uKsQwu7QCpfV+ufjsAZCf7GMndy8QeLqc3ZU+/9CV2w7pr1aX76B/tB2fHZ9GcuvlzENA0uyeZm/hh62i0zc2SNe5tpiZS9o/t1kE60giJNmT+FD3MV4OKkKu/XFrTVSMcjzjVcX5TrK4oL2ox0CmDny2jF9CVVQ5enaSLDzFCy4nU44OAlFi7mzgk2y8P4PMVnGINAUZ7bHqy2Z50HLNmt8xB5zgi6NxfOVv2E9u5efGk50p3peqf50O8mX/GR7x6Kbx2JUYMfokKNlw1jxPP6VravbZhkwnUsk/zJwoNRbocHgRm2iTI/mD7SE79LJcTmv9iKX02oc79OhSkOv/jNmt2KoJRWtny1wMW99hB1tidqax2Ao1v0YePEiS9cnLOv003wiojIlFxcZUD/G7XFgbDzIv7rgv+lT895CDIlTfqHHUesmk9VjSj06x5EPimEL4X5LoZXlBbS8fYp6jgHqZLM7EYcxdrhsgkFyMYqINw+2SCHLUhB13On2d2wGq/WP4HM=}
